//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoEco.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoEcoEntities : DbContext
    {
        public CoEcoEntities()
            : base("name=CoEcoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemToUnit> ItemToUnits { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<IconStore> IconStores { get; set; }
        public virtual DbSet<RatingQuestion> RatingQuestions { get; set; }
        public virtual DbSet<PermissionsProfile> PermissionsProfiles { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MembersFileError> MembersFileErrors { get; set; }
        public virtual DbSet<DistanceUnit> DistanceUnits { get; set; }
        public virtual DbSet<LendingItem> LendingItems { get; set; }
        public virtual DbSet<OrderDataReport> OrderDataReports { get; set; }
    }
}
