//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoEco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message : CoEco.Data.EntityTypes.IBaseEntity
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string Content { get; set; }
        public int OrderID { get; set; }
        public int MemberID { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool Disable { get; set; }
    
        public virtual Member Members { get; set; }
        public virtual LendingItem LendingItem { get; set; }
    }
}
