//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoEco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDataReport : CoEco.Data.EntityTypes.IBaseEntity
    {
        public string Name { get; set; }
        public int Cost { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string StatusName { get; set; }
        public Nullable<double> RatingRequestUnit { get; set; }
        public Nullable<double> RatingLendingUnit { get; set; }
        public double Distance { get; set; }
        public string ProblemDescriptionRequestUnit { get; set; }
        public string ProblemDescriptionLendingUnit { get; set; }
        public Nullable<int> RequestingUnitCurrentWheelQuantity { get; set; }
        public string RequestingUnitName { get; set; }
        public Nullable<int> LendingUnitCurrentWheelQuantity { get; set; }
        public string LendingUnitName { get; set; }
        public int UnitRequestsID { get; set; }
        public int UnitLendingID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool Disable { get; set; }
        public int StatusID { get; set; }
    }
}
