//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגעת למגבלת ההתחברויות של המשתמש, נא לנסות עם משתמש אחר או מאוחר יותר.
        /// </summary>
        internal static string Auth_ConnectionPoolIsFull {
            get {
                return ResourceManager.GetString("Auth_ConnectionPoolIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שליחת ה SMS נכשלה.
        /// </summary>
        internal static string Auth_FailedToSendSms {
            get {
                return ResourceManager.GetString("Auth_FailedToSendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד לא תקין.
        /// </summary>
        internal static string Auth_InvalidCode {
            get {
                return ResourceManager.GetString("Auth_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יותר מדי נסיונות.
        /// </summary>
        internal static string Auth_TooManyFails {
            get {
                return ResourceManager.GetString("Auth_TooManyFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש לא קיים.
        /// </summary>
        internal static string Auth_UserNotFound {
            get {
                return ResourceManager.GetString("Auth_UserNotFound", resourceCulture);
            }
        }
    }
}
