//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסיסמאות אינן תואמות.
        /// </summary>
        internal static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% מספר כרטיס אשראי אינו תקין.
        /// </summary>
        internal static string creditCard {
            get {
                return ResourceManager.GetString("creditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% צריך להיות תאריך.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות מחרוזת משך ISO8601, כגון &apos;P3H24M60S&apos;.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת מייל לא חוקית.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת מייל לא חוקית.
        /// </summary>
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName%  חייב להיות GUID.
        /// </summary>
        internal static string guid {
            get {
                return ResourceManager.GetString("guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות ערך מספרי.
        /// </summary>
        internal static string int32 {
            get {
                return ResourceManager.GetString("int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות ערך מספרי.
        /// </summary>
        internal static string int64 {
            get {
                return ResourceManager.GetString("int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות ערך מספרי.
        /// </summary>
        internal static string integer {
            get {
                return ResourceManager.GetString("integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות ערך מספרי.
        /// </summary>
        internal static string integerRange {
            get {
                return ResourceManager.GetString("integerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדה תוקף הינו שדה חובה.
        /// </summary>
        internal static string InvalidAccountExpiresAt {
            get {
                return ResourceManager.GetString("InvalidAccountExpiresAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת מייל לא חוקית.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% ארוך/ה מדי.
        /// </summary>
        internal static string maxLength {
            get {
                return ResourceManager.GetString("maxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% קצר/ה מידי.
        /// </summary>
        internal static string minlength {
            get {
                return ResourceManager.GetString("minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות ערך מספרי.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נדרשת ספרה אחת.
        /// </summary>
        internal static string PasswordRequireDigit {
            get {
                return ResourceManager.GetString("PasswordRequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נדרשת אות קטנה אחת.
        /// </summary>
        internal static string PasswordRequireLower {
            get {
                return ResourceManager.GetString("PasswordRequireLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נדרשת ספרה או תו שאינו אות.
        /// </summary>
        internal static string PasswordRequireNonLetterOrDigit {
            get {
                return ResourceManager.GetString("PasswordRequireNonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נדרשת אות גדולה אחת.
        /// </summary>
        internal static string PasswordRequireUpper {
            get {
                return ResourceManager.GetString("PasswordRequireUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמה קצרה מידי.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% לא תקין.
        /// </summary>
        internal static string pattern {
            get {
                return ResourceManager.GetString("pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר טלפון לא חוקי.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% %value% אינו תואם לביטוי %expression%&apos;&quot;.
        /// </summary>
        internal static string regularExpression {
            get {
                return ResourceManager.GetString("regularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% הוא שדה חובה.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %displayName% חייב להיות מחרוזת עם אורך מ %minLength% עד %maxLength% תווים.
        /// </summary>
        internal static string stringLength {
            get {
                return ResourceManager.GetString("stringLength", resourceCulture);
            }
        }
    }
}
