//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoEco.Core.Ordering.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoEco.Core.Ordering.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפריט שהושאל מיחידתך הגיע ליעדו.
        /// </summary>
        internal static string OrderActivated {
            get {
                return ResourceManager.GetString("OrderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נפתחה ביחידה אחרת בקשה להשאלת פריט לאישורך.
        /// </summary>
        internal static string OrderApproved {
            get {
                return ResourceManager.GetString("OrderApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בקשתך להשאלת פריט נדחתה ע&quot;י היחידה בעלת הפריט.
        /// </summary>
        internal static string OrderCanceledByLendingUnit {
            get {
                return ResourceManager.GetString("OrderCanceledByLendingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בקשתך להשאלת פריט נדחתה ביחידתך.
        /// </summary>
        internal static string OrderCanceledByRequestingUnit {
            get {
                return ResourceManager.GetString("OrderCanceledByRequestingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השאלת הפריט ליחידתך הסתיימה.
        /// </summary>
        internal static string OrderCompleted {
            get {
                return ResourceManager.GetString("OrderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בקשתך להשאלת פריט אושרה ע&quot;י היחידה בעלת הפריט. הפריט ממתין להעברה.
        /// </summary>
        internal static string OrderConfirmed {
            get {
                return ResourceManager.GetString("OrderConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נפתחה ביחידתך בקשה להשאלת פריט לאישורך.
        /// </summary>
        internal static string OrderOpened {
            get {
                return ResourceManager.GetString("OrderOpened", resourceCulture);
            }
        }
    }
}
